version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
  api-eventos:
    image: gabriel94dantas/api-eventos-image:latest
    depends_on:
        - broker
    hostname: api-eventos
    container_name: api-eventos
    ports:
        - 80:80
    environment:
        - BROKER_HOST=broker:29092
  api-eventos-java-quarkus:
    image: gabriel94dantas/api-eventos-quarkus:latest
    depends_on:
      - broker
    hostname: api-eventos-java-quarkus
    container_name: api-eventos-java-quarkus
    ports:
        - 8080:8080
    environment:
      - BROKER_HOST=broker:29092
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - 27017:27017
  consumer-eventos-quarkus:
    image: gabriel94dantas/consumer-kafka-quarkus:latest
    depends_on:
      - broker
      - mongo
    hostname: consumer-eventos-quarkus
    container_name: consumer-eventos-quarkus
    ports:
      - 8082:8080
    environment:
      - BROKER_HOST=broker:29092
      - MONGO_HOST=mongodb://mongo:27017
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00T12#
      MYSQL_DATABASE: marketplacedb
      MYSQL_HOST: jdbc:mysql://localhost:3306/marketplacedb
      MYSQL_PASSWORD: r00T12#
      MYSQL_APP_USER: root
    ports:
      - '3306:3306'